name: Build & Release 

on:
  push:
    branches: 
      - main
  workflow_dispatch: # релиз по кнопке

jobs:
  build:
    runs-on: windows-latest 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure Makefile
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Upload 
      uses: actions/upload-artifact@v4
      with:
        name: ghost_window
        path: build/Release/*.exe